# Generated by Django 6.0.5 on 2026-06-01 17:51

import broadcast_dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='main', max_length=100, unique=True)),
                ('value', models.JSONField(default=broadcast_dashboard.models.default_dashboard_settings)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
